const THEMES = {
	default: {
		name: 'Default',
		properties: {
			'brand-color': '#7c87e8',
			'body-background-color': '#C3D1F5',
			'select-table-background-color': '#f6f6f6',
			'alternate-table-item-color': '#ECEBFE',
			'card-background-color': '#ffffff',
			'card-highlight-color': '#ECEBFE',
			'timetable-lab-color': '#99D1FF',
			'timetable-theory-color': '#FFDCB5',
			'timetable-col1-color': '#e5e5e5',
			'button-highlight-color': '#36e2a8',
			'text-color-default': '#ffffff',
			'text-color-inverted': '#000000',
			'text-color-other': '#666666',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#00b200',
			'dropdown-border-color': '#4c56b2',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#00000059',
		},
	},
	dark: {
		name: 'Eerie Black',
		properties: {
			'brand-color': '#121317',
			'body-background-color': '#15181f',
			'select-table-background-color': '#1f2229',
			'alternate-table-item-color': '#1f2229',
			'card-background-color': '#27282C',
			'card-highlight-color': '#4993D0',
			'timetable-lab-color': '#008C7E',
			'timetable-theory-color': '#6B4896',
			'timetable-col1-color': '#121317',
			'button-highlight-color': '#36e2a8',
			'text-color-default': '#ffffff',
			'text-color-inverted': '#ffffff',
			'text-color-other': '#ffffff',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#ffffff',
			'dropdown-border-color': '#1f2229',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#000000',
		},
	},
	yellowish: {
		name: 'Mellow Yellow',
		properties: {
			'brand-color': '#FFDA76',
			'body-background-color': '#FFECC5',
			'select-table-background-color': '#f6f6f6',
			'alternate-table-item-color': '#FFFAE9',
			'card-background-color': '#ffffff',
			'card-highlight-color': '#FFFAE9',
			'timetable-lab-color': '#99D1FF',
			'timetable-theory-color': '#FFDCB5',
			'timetable-col1-color': '#e5e5e5',
			'button-highlight-color': '#36e2a8',
			'text-color-default': '#2F4F4F',
			'text-color-inverted': '#2F4F4F',
			'text-color-other': '#666666',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#00b200',
			'dropdown-border-color': '#FFD156',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#00000059',
		},
	},
	coral: {
		name: 'Light Coral',
		properties: {
			'brand-color': '#E87A85',
			'body-background-color': '#F4C3D1',
			'select-table-background-color': '#f6f6f6',
			'alternate-table-item-color': '#FFEDED',
			'card-background-color': '#ffffff',
			'card-highlight-color': '#FFEDED',
			'timetable-lab-color': '#99D1FF',
			'timetable-theory-color': '#FFDCB5',
			'timetable-col1-color': '#e5e5e5',
			'button-highlight-color': '#36e2a8',
			'text-color-default': '#ffffff',
			'text-color-inverted': '#000000',
			'text-color-other': '#666666',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#00b200',
			'dropdown-border-color': '#B24C56',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#00000059',
		},
	},
	green: {
		name: 'Pretty Green',
		properties: {
			'brand-color': '#7AE88B',
			'body-background-color': '#C6F4C3',
			'select-table-background-color': '#f6f6f6',
			'alternate-table-item-color': '#EDFFF2',
			'card-background-color': '#ffffff',
			'card-highlight-color': '#EDFFF2',
			'timetable-lab-color': '#99D1FF',
			'timetable-theory-color': '#FFDCB5',
			'timetable-col1-color': '#e5e5e5',
			'button-highlight-color': '#f4c2c6',
			'text-color-default': '#2F4F4F',
			'text-color-inverted': '#000000',
			'text-color-other': '#666666',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#00b200',
			'dropdown-border-color': '#4CB25C',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#00000059',
		},
	},
	blue: {
		name: 'Devspace Light',
		properties: {
			'brand-color': '#7AD7E8',
			'body-background-color': '#C3F4F2',
			'select-table-background-color': '#f6f6f6',
			'alternate-table-item-color': '#EDF9FF',
			'card-background-color': '#ffffff',
			'card-highlight-color': '#EDF9FF',
			'timetable-lab-color': '#99D1FF',
			'timetable-theory-color': '#FFDCB5',
			'timetable-col1-color': '#e5e5e5',
			'button-highlight-color': '#36e2a8',
			'text-color-default': '#2F4F4F',
			'text-color-inverted': '#000000',
			'text-color-other': '#666666',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#00b200',
			'dropdown-border-color': '#1d98ae',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#00000059',
		},
	},
	pink: {
		name: 'Persian Pink',
		properties: {
			'brand-color': '#E87ABC',
			'body-background-color': '#F4C3E9',
			'select-table-background-color': '#f6f6f6',
			'alternate-table-item-color': '#FFEDF4',
			'card-background-color': '#ffffff',
			'card-highlight-color': '#FFEDF4',
			'timetable-lab-color': '#99D1FF',
			'timetable-theory-color': '#FFDCB5',
			'timetable-col1-color': '#e5e5e5',
			'button-highlight-color': '#36e2a8',
			'text-color-default': '#ffffff',
			'text-color-inverted': '#000000',
			'text-color-other': '#666666',
			'card-clash-text-color': '#ff6961',
			'card-selected-text-color': '#00b200',
			'dropdown-border-color': '#B24C89',
			'dropshadow-default': '#00000033',
			'dropshadow-highlight': '#00000059',
		},
	},
};

export default THEMES;
