name: Node-Server-Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: 'ffcs'
          key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          port: 22
          script: |
            cd /home/ffcs
            rm -rf FFCSThingy2.0
            git clone https://github.com/FFCSThingy/FFCSThingy2.0.git
            cd FFCSThingy2.0/backend
            docker build -t ffcs-backend .
            docker stop ffcs-backend || true
            docker rm ffcs-backend || true
            docker run -d -p 3001:3001 --name ffcs-backend ffcs-backend
