name: Node-Server-Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: 'root'
          key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          port: 22
          script: |
            cd /root/FFCSThingy2.0/backend
            git pull origin master
            docker kill backend || true  
            docker build -t ffcsbackend .
            docker run -d --rm -p 3000:3000 --name backend ffcsbackend
