name: Node-Server-Deploy

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: 'ffcs'
          key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          port: 22
          script: |
            cd /home/ffcs/FFCSThingy2.0/backend
            git reset HEAD --hard
            git pull origin master
            docker-compose up -d --build
